#!/bin/bash
clang -g -Wall -DAX_OSX=1 -Wno-null-dereference -c osx_main.mm
clang -g -Wall -DAX_OSX=1 -Wno-null-dereference -c NavWindow.mm
clang -g -Wall -DAX_OSX=1 -Wno-null-dereference -c NavView.mm
clang -g -Wall -DAX_OSX=1 -Wno-null-dereference -framework Cocoa -framework QuartzCore -framework OpenGL -framework IOKit -framework AudioUnit -o Nelson osx_main.o NavWindow.o NavView.o
